
import React from 'react';
import { Link } from 'react-router-dom';
import { AppRoute } from '../types';

const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 selection:bg-indigo-100 selection:text-indigo-900">
      <nav className="glass-nav sticky top-0 z-50 border-b border-slate-200/50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to={AppRoute.LANDING} className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-black text-sm shadow-md">T</div>
            <span className="font-extrabold text-lg tracking-tight text-slate-800">TaskFlow</span>
          </Link>
          <Link to={AppRoute.LANDING} className="text-sm font-bold text-slate-500 hover:text-indigo-600 transition-colors">Back to Home</Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-20">
        <div className="bg-white rounded-[2.5rem] p-10 sm:p-16 border border-slate-100 shadow-xl shadow-slate-200/50">
          <h1 className="text-4xl sm:text-5xl font-black mb-8 tracking-tight italic">Terms of Service</h1>
          <p className="text-slate-400 text-sm font-bold mb-12 uppercase tracking-widest">Effective Date: October 2023</p>

          <div className="prose prose-slate max-w-none space-y-12">
            <section>
              <h2 className="text-2xl font-black mb-4 flex items-center gap-3">
                <span className="w-8 h-8 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center text-sm">01</span>
                Acceptance of Terms
              </h2>
              <p className="text-slate-600 leading-relaxed font-medium">
                By accessing or using TaskFlow, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, you should not access or use our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-black mb-4 flex items-center gap-3">
                <span className="w-8 h-8 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center text-sm">02</span>
                User Responsibility
              </h2>
              <p className="text-slate-600 leading-relaxed font-medium">
                You are responsible for maintaining the confidentiality of your account information. Since TaskFlow stores data locally, you are responsible for the security of your device and the browser environment in which you use the application.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-black mb-4 flex items-center gap-3">
                <span className="w-8 h-8 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center text-sm">03</span>
                AI Disclaimer
              </h2>
              <p className="text-slate-600 leading-relaxed font-medium">
                Our AI features provide suggestions generated by automated models. While we strive for accuracy, TaskFlow does not guarantee the quality, correctness, or usefulness of any AI-generated content. Use AI suggestions at your own discretion.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-black mb-4 flex items-center gap-3">
                <span className="w-8 h-8 rounded-xl bg-rose-50 text-rose-600 flex items-center justify-center text-sm">04</span>
                Limitation of Liability
              </h2>
              <p className="text-slate-600 leading-relaxed font-medium">
                TaskFlow is provided "as is" without warranty of any kind. We shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our services.
              </p>
            </section>
          </div>

          <div className="mt-20 pt-10 border-t border-slate-100 text-center">
            <p className="text-slate-400 text-sm font-medium">Questions about these terms? Reach out at legal@taskflow.io</p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Terms;
